clear;
clc;
close all;
[x,Fs] = audioread('handel.wav');
N = 64;
L = 5;
xx = reshape(x, [length(x)/N, N]);
YY = fft(xx, N, 2);
YY(:, L+1:end) = 0;
%YY(:, end:-1:end-L+1) = conj(YY(:, 1:L));
yy = real(ifft(YY, N, 2));
y = reshape(yy, [length(x), 1]);
sound(y, Fs);